/**
 * Edit these defaults or override location settings with URL parameters:
 * ?lat=52.4357&lon=13.5406&name=Berlin-Adlershof&timezone=Europe/Berlin
 */
export const DEFAULT_CONFIG = Object.freeze({
  version: "3.16.0",
  latitude: 52.4357,
  longitude: 13.5406,
  locationName: "Berlin-Adlershof",
  timezone: "Europe/Berlin",
  locale: "de-DE",
  language: "en",
  iconPack: "fill",
  // Keep credentials and required identification headers in a server-side proxy.
  weatherProvider: "openMeteoDwd",
  providerProxyUrl: "",
  themeMode: "auto",
  colorTheme: "default",
  customBgColor: "#0f172a",
  customTileColor: "#1e293b",
  customTextColor: "#f8fafc",
  customAccentColor: "#38bdf8",
  customChipColor: "#334155",
  layoutStructure: "default",
  bgImageType: "none",
  bgImageUrl: "",
  bgImageDataUrl: "",
  bgPresetUrl: "",
  tileOpacity: 0.75,
  fontScale: 1,
  density: "comfortable",
  informationMode: "detailed",
  forecastRotation: "auto",
  yearProgressMode: "both",
  secondaryInfoMode: "autoHide",
  secondaryInfoDelaySeconds: 15,
  layoutMode: "auto",
  deviceProfile: "auto",
  displayScale: 1,
  contentWidthPercent: 100,
  frameInsetMode: "uniform",
  frameInset: 0,
  frameInsetTop: 0,
  frameInsetRight: 0,
  frameInsetBottom: 0,
  frameInsetLeft: 0,
  controlsAutoHideSeconds: 8,
  refreshIntervalMinutes: 10,
  flipIntervalSeconds: 30,
  retryIntervalSeconds: 60,
  cacheMaxAgeHours: 12,
  forecastDays: 7,
});
